name: Github action for Docker to ECR


on:
 push:
  branches: main
 
 pull_request:
  branches: main
  
  
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
 
  
 
 
 
 
 
 
