  
  
  
  
  
  

name: Github action for Docker to ECR


on:
 push:
  branches: master
  
  
  

jobs:
  
    
  
  ECRbuild:
    name: Run Docker and Push to ECR
    runs-on: ubuntu-20.04
    steps:
        
        
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: AWS cred
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}
            
                   
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1


          
          
      - name: ECRtask
        id: ECRtaskrun
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: st_cloud_first_version
          IMAGE_TAG: latest
        run: |
          df -h
          ls
          echo $ { GITHUB_WORKSPACE }
          
          #docker rmi `docker images -q`
          docker pull tensorflow/tensorflow
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          df -h
          docker tag tensorflow/tensorflow:latest 224066078089.dkr.ecr.us-east-2.amazonaws.com/st_cloud_first_version:latest
          echo "Pushing image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          

          
